spring:
 application:
   name: PAPER-WEB
 cloud:
   loadbalancer:
     retry:
       enabled: true
 thymeleaf:
   mode: LEGACYHTML5
   cache: false
   suffix: .html
   encoding: UTF-8
   content-type: text/html


server:
  port: 30002

management:
  security:
    enabled: false
#eureka服务发现
eureka:
  client:
    service-url:
     defaultZone: http://123.206.24.171:1111/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    hostname: ${spring.cloud.client.ipAddress}
    ip-address: 123.206.24.171
feign:
 hystrix:
  enable: true